spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update

server:
  port: ${PORT:8080}

app:
  password-reset:
    expose-development-token: false
