package com.mockmate.interview;

import com.mockmate.ai.AiInterviewService; import com.mockmate.user.*; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.HttpStatus; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @Transactional @RequestMapping("/api/interviews") public class InterviewController {
 private final InterviewRepository interviews; private final UserRepository users; private final AiInterviewService ai;
 InterviewController(InterviewRepository i,UserRepository u,AiInterviewService a){interviews=i;users=u;ai=a;}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) InterviewView start(@Valid @RequestBody StartRequest r,Authentication auth){User u=current(auth);Interview x=new Interview();x.setUser(u);x.setType(r.type());x.setTargetRole(r.targetRole());String resume="";for(String q:ai.generateQuestions(r.type(),r.targetRole(),resume,r.questionCount())){InterviewQuestion iq=new InterviewQuestion();iq.setInterview(x);iq.setQuestion(q);x.getQuestions().add(iq);}return view(interviews.save(x));}
 @GetMapping List<InterviewView> list(Authentication auth){return interviews.findByUserOrderByCreatedAtDesc(current(auth)).stream().map(this::view).toList();}
 @GetMapping("/{id}") InterviewView get(@PathVariable Long id,Authentication auth){return view(owned(id,auth));}
 @PostMapping("/{id}/questions/{questionId}/answer") QuestionView answer(@PathVariable Long id,@PathVariable Long questionId,@Valid @RequestBody AnswerRequest r,Authentication auth){Interview x=owned(id,auth);InterviewQuestion q=x.getQuestions().stream().filter(v->v.getId().equals(questionId)).findFirst().orElseThrow(()->new IllegalArgumentException("Question not found"));q.setAnswer(r.answer());var e=ai.evaluate(x.getType(),q.getQuestion(),r.answer());q.setScore(e.score());q.setFeedback(e.feedback());interviews.save(x);return question(q);}
 @PostMapping("/{id}/complete") InterviewView complete(@PathVariable Long id,Authentication auth){Interview x=owned(id,auth);var answered=x.getQuestions().stream().filter(q->q.getScore()!=null).toList();if(answered.isEmpty())throw new IllegalArgumentException("Answer at least one question before completing");x.setScore((int)Math.round(answered.stream().mapToInt(InterviewQuestion::getScore).average().orElse(0)));x.setStatus("COMPLETED");x.setWeaknessAnalysis(String.join(", ",answered.stream().flatMap(q->ai.evaluate(x.getType(),q.getQuestion(),q.getAnswer()).weaknesses().stream()).distinct().toList()));return view(interviews.save(x));}
 private User current(Authentication a){return users.findByEmail(a.getName()).orElseThrow(()->new SecurityException("User not found"));} private Interview owned(Long id,Authentication a){return interviews.findByIdAndUser(id,current(a)).orElseThrow(()->new IllegalArgumentException("Interview not found"));}
 private InterviewView view(Interview x){return new InterviewView(x.getId(),x.getType(),x.getTargetRole(),x.getStatus(),x.getScore(),x.getWeaknessAnalysis(),x.getCreatedAt(),x.getQuestions().stream().map(this::question).toList());} private QuestionView question(InterviewQuestion q){return new QuestionView(q.getId(),q.getQuestion(),q.getAnswer(),q.getScore(),q.getFeedback());}
 record StartRequest(@NotNull InterviewType type,@NotBlank String targetRole,@Min(1) @Max(10) int questionCount){} record AnswerRequest(@NotBlank @Size(max=6000) String answer){} record QuestionView(Long id,String question,String answer,Integer score,String feedback){} record InterviewView(Long id,InterviewType type,String targetRole,String status,Integer score,String weaknessAnalysis,java.time.Instant createdAt,List<QuestionView> questions){}
}
