import { useEffect, useState } from 'react'
import { request, token } from './api'

const types = [
  ['HR', 'HR Interview', 'Culture, communication, and confidence'],
  ['TECHNICAL', 'Technical Interview', 'System design, APIs, and databases'],
  ['JAVA', 'Java Interview', 'Core Java, OOP, Spring, and JVM'],
  ['DSA', 'DSA Interview', 'Algorithms, data structures, and complexity'],
]

export default function App() {
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('mockmate_user') || 'null'))
  const [page, setPage] = useState(token() ? 'dashboard' : 'auth')
  const [dashboard, setDashboard] = useState(null)
  const [interview, setInterview] = useState(null)
  const [message, setMessage] = useState('')

  const loadDashboard = async () => { try { setDashboard(await request('/dashboard')) } catch { logout() } }
  useEffect(() => { if (token()) loadDashboard() }, [])
  const logout = () => { localStorage.removeItem('mockmate_token'); localStorage.removeItem('mockmate_user'); setUser(null); setDashboard(null); setPage('auth') }
  const notify = (value) => { setMessage(value); setTimeout(() => setMessage(''), 3500) }
  const authSuccess = (data) => { localStorage.setItem('mockmate_token', data.token); localStorage.setItem('mockmate_user', JSON.stringify({ name: data.name, email: data.email })); setUser({ name: data.name, email: data.email }); setPage('dashboard'); loadDashboard() }
  const begin = async (type, targetRole = 'Software Developer', questionCount = 3) => { try { const created = await request('/interviews', { method: 'POST', body: JSON.stringify({ type, targetRole, questionCount }) }); setInterview(created); setPage('interview') } catch (e) { notify(e.message) } }
  const completed = () => { setPage('results'); loadDashboard() }

  return <div className="app-shell">
    {message && <div className="toast">{message}</div>}
    {user && <header><button className="brand" onClick={() => setPage('dashboard')}><span>✦</span> MockMate</button><nav><button onClick={() => setPage('dashboard')}>Dashboard</button><button onClick={() => setPage('setup')}>Practice</button><button onClick={() => setPage('resume')}>Resume</button><button className="avatar" onClick={logout} title="Log out">{user.name[0]}</button></nav></header>}
    <main>
      {page === 'auth' && <Auth onSuccess={authSuccess} />}
      {page === 'dashboard' && <Dashboard user={user} data={dashboard} onPractice={() => setPage('setup')} onResume={() => setPage('resume')} />}
      {page === 'setup' && <Setup onStart={begin} />}
      {page === 'interview' && interview && <InterviewRoom interview={interview} onComplete={completed} notify={notify} />}
      {page === 'results' && interview && <Results interview={interview} onPractice={() => setPage('setup')} />}
      {page === 'resume' && <Resume notify={notify} />}
    </main>
  </div>
}

function Auth({ onSuccess }) {
  const [register, setRegister] = useState(false), [form, setForm] = useState({ name: '', email: '', password: '' }), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { onSuccess(await request(`/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(register ? form : { email: form.email, password: form.password }) })) } catch (x) { setError(x.message) } finally { setBusy(false) } }
  return <section className="auth"><div className="hero"><span className="eyebrow">AI-POWERED INTERVIEW PRACTICE</span><h1>Walk into your next interview ready.</h1><p>Practice with a personal AI interviewer, get honest feedback, and turn weak points into strengths.</p><div className="hero-stats"><b>4</b> interview tracks <b>Instant</b> feedback <b>Private</b> practice</div></div><form className="auth-card" onSubmit={submit}><span className="logo-mark">✦</span><h2>{register ? 'Create your account' : 'Welcome back'}</h2><p>{register ? 'Start practising smarter today.' : 'Continue your interview journey.'}</p>{register && <label>Full name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label>}<label>Email<input type="email" required value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Password<input type="password" required minLength="8" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>{error && <small className="error">{error}</small>}<button className="primary wide" disabled={busy}>{busy ? 'Please wait…' : register ? 'Create account' : 'Sign in'}</button><button type="button" className="link" onClick={() => setRegister(!register)}>{register ? 'Already have an account? Sign in' : 'New to MockMate? Create an account'}</button></form></section>
}

function Dashboard({ user, data, onPractice, onResume }) { const score = data?.averageScore ?? 0; return <><section className="welcome"><div><span className="eyebrow">YOUR PRACTICE SPACE</span><h1>Good evening, {user?.name?.split(' ')[0]}.</h1><p>Small practice sessions create big interview confidence.</p></div><button className="primary" onClick={onPractice}>Start an interview <span>→</span></button></section><section className="metrics"><Metric label="Interviews completed" value={data?.completedInterviews ?? 0} icon="◎"/><Metric label="Average score" value={`${score}%`} icon="↗"/><Metric label="Interview tracks" value="4" icon="◈"/></section><section className="dashboard-grid"><div className="panel"><div className="panel-title"><h2>Practice by track</h2><button className="link" onClick={onPractice}>View all</button></div><div className="tracks">{types.map(([key, title, text]) => <button className="track" key={key} onClick={onPractice}><span className="track-icon">{key === 'JAVA' ? '☕' : key === 'DSA' ? '⌘' : key === 'HR' ? '♡' : '◇'}</span><div><b>{title}</b><small>{text}</small></div><span>→</span></button>)}</div></div><div className="panel insight"><span className="eyebrow">AI INSIGHT</span><h2>{score ? `Your average score is ${score}%.` : 'Your first practice starts here.'}</h2><p>{score ? 'Keep answers structured: context, action, result. Specific examples make your impact memorable.' : 'Choose an interview track and receive tailored questions in seconds.'}</p><button className="secondary" onClick={onResume}>Upload resume</button></div></section></> }
function Metric({ label, value, icon }) { return <div className="metric"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div> }
function Setup({ onStart }) { const [role, setRole] = useState('Software Developer'), [count, setCount] = useState(3); const start = (type) => onStart(type, role, count); return <section className="setup"><span className="eyebrow">NEW PRACTICE SESSION</span><h1>Choose your interview track.</h1><p>Your AI interviewer will tailor questions to help you practise with purpose.</p><div className="setup-options"><label>Target role<input value={role} onChange={e => setRole(e.target.value)} /></label><label>Questions<select value={count} onChange={e => setCount(Number(e.target.value))}><option value="3">3 questions · Quick</option><option value="5">5 questions · Standard</option></select></label></div><div className="choose-grid">{types.map(([key, title, text]) => <button key={key} onClick={() => start(key)}><span>{key === 'JAVA' ? '☕' : key === 'DSA' ? '⌘' : key === 'HR' ? '♡' : '◇'}</span><h2>{title}</h2><p>{text}</p><small>Start practice →</small></button>)}</div></section> }

function InterviewRoom({ interview, onComplete, notify }) {
  const [session, setSession] = useState(interview), [index, setIndex] = useState(0), [answer, setAnswer] = useState(''), [loading, setLoading] = useState(false)
  const question = session.questions[index]
  const submit = async () => { if (!answer.trim()) return notify('Write or dictate an answer first.'); setLoading(true); try { const updated = await request(`/interviews/${session.id}/questions/${question.id}/answer`, { method: 'POST', body: JSON.stringify({ answer }) }); const questions = [...session.questions]; questions[index] = { ...questions[index], ...updated }; setSession({ ...session, questions }); if (index < questions.length - 1) { setIndex(index + 1); setAnswer(questions[index + 1].answer || '') } else notify('Answer saved. Complete the interview when you are ready.') } catch (e) { notify(e.message) } finally { setLoading(false) } }
  const finish = async () => { try { let finalSession = session; if (question.score == null) { if (!answer.trim()) return notify('Write or dictate an answer first.'); const updated = await request(`/interviews/${session.id}/questions/${question.id}/answer`, { method: 'POST', body: JSON.stringify({ answer }) }); const questions = [...session.questions]; questions[index] = { ...questions[index], ...updated }; finalSession = { ...session, questions }; setSession(finalSession) } const done = await request(`/interviews/${session.id}/complete`, { method: 'POST' }); interview.score = done.score; interview.weaknessAnalysis = done.weaknessAnalysis; interview.questions = done.questions; onComplete() } catch (e) { notify(e.message) } }
  const dictate = () => { const Speech = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Speech) return notify('Speech recognition is not supported in this browser.'); const recognition = new Speech(); recognition.lang = 'en-US'; recognition.onresult = e => setAnswer(v => `${v} ${e.results[0][0].transcript}`.trim()); recognition.start() }
  return <section className="interview-room"><aside><span className="eyebrow">{session.type} INTERVIEW</span><h2>{session.targetRole}</h2><div className="progress"><i style={{ width: `${((index + 1) / session.questions.length) * 100}%` }} /></div><p>Question {index + 1} of {session.questions.length}</p>{session.questions.map((q, n) => <button className={n === index ? 'active-dot' : ''} key={q.id} onClick={() => { setIndex(n); setAnswer(q.answer || '') }}>{n + 1} {q.score != null && '✓'}</button>)}</aside><div className="question-area"><span className="question-label">QUESTION {index + 1}</span><h1>{question.question}</h1><p>Take a moment to structure your response. A strong answer explains the situation, your action, and the result.</p><textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="Type your answer here…" /><div className="answer-actions"><button className="secondary" onClick={dictate}>◉ Dictate answer</button>{index === session.questions.length - 1 ? <button className="primary" onClick={finish}>Complete interview →</button> : <button className="primary" disabled={loading} onClick={submit}>{loading ? 'Saving…' : 'Save & next →'}</button>}</div>{question.feedback && <div className="feedback"><b>AI feedback · {question.score}/100</b><p>{question.feedback}</p></div>}</div></section>
}
function Results({ interview, onPractice }) { return <section className="results"><span className="eyebrow">SESSION COMPLETE</span><h1>Nice work. Here’s your feedback.</h1><div className="score"><b>{interview.score ?? 0}</b><span>/100</span></div><p className="score-caption">Your {interview.type.toLowerCase()} interview score</p><div className="results-grid"><div className="panel"><h2>Growth opportunities</h2><p>{interview.weaknessAnalysis || 'Continue practising concise, structured answers with concrete examples.'}</p></div><div className="panel"><h2>Question feedback</h2>{interview.questions.map((q, i) => <div className="result-row" key={q.id}><span>{i + 1}</span><div><b>{q.score ?? 0}/100</b><p>{q.feedback || 'Not answered'}</p></div></div>)}</div></div><button className="primary" onClick={onPractice}>Practice another track →</button></section> }
function Resume({ notify }) { const [file, setFile] = useState(null), [busy, setBusy] = useState(false); const upload = async e => { e.preventDefault(); if (!file) return notify('Choose a PDF or DOCX resume.'); setBusy(true); const body = new FormData(); body.append('file', file); try { const data = await request('/resume', { method: 'POST', body }); notify(data.message) } catch (x) { notify(x.message) } finally { setBusy(false) } }; return <section className="resume"><span className="eyebrow">YOUR PROFILE</span><h1>Upload your resume.</h1><p>We use your experience to make questions more relevant. Your file is private to your account.</p><form onSubmit={upload} className="upload-zone"><input id="resume" type="file" accept=".pdf,.docx" onChange={e => setFile(e.target.files[0])} /><label htmlFor="resume"><span>↑</span><b>{file ? file.name : 'Choose your resume'}</b><small>PDF or DOCX · Maximum 10 MB</small></label><button className="primary" disabled={busy}>{busy ? 'Uploading…' : 'Upload resume'}</button></form></section> }
